[template]
src = "haproxy_exporter-settings.env.tmpl"
dest = "/etc/haproxy_exporter-settings.env"
keys = [
  "/self",
  "/containers",
]
mode = "0755"
reload_cmd = "/usr/bin/sv force-reload haproxy_exporter"
